export const FORM_PROYECT = 'FORM_PROYECT'
export const GET_PROYECT = 'GET_PROYECT'
export const ADD_PROYECT = 'ADD_PROYECT'
export const CURRENT_PROYECT = 'CURRENT_PROYECT'
export const DELETE_PROYECT = 'DELETE_PROYECT'
export const ERROR_PROYECT = 'ERROR_PROYECT'

export const TASKS_PROYECT = 'TASKS_PROYECT'
export const ADD_TASK = 'ADD_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const SELECT_TASK = 'SELECT_TASK'
export const UPTDATE_TASK = 'UPTDATE_TASK'
export const RESET_TASK = 'RESET_TASK'


export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'

export const REGISTER_SECCESS = 'REGISTER_SECCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const GET_USER = 'GET_USER'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const CLOSE_SESSION = 'CLOSE_SESSION'