export const Formulario_proyecto = 'Formulario_proyecto'
export const Obtener_proyecto = 'Obtener_proyecto'
export const Agregar_proyecto = 'Agregar_proyecto'
export const Actual_proyecto = 'Actual_proyecto'
export const Eliminar_proyecto = 'Eliminar_proyecto'

export const Tareas_proyecto = 'Tareas_proyecto'
export const Agregar_tarea = 'Agregar_tarea'
export const Eliminar_tarea = 'Eliminar_tarea'
export const Estado_tarea = 'Estado_tarea'
export const Seleccionar_tarea = 'Seleccionar_tarea'
export const Actualizar_tarea = 'Actualizar_tarea'

export const Mostrar_alerta = 'Mostrar_alerta'
export const Ocultar_alerta = 'Ocultar_alerta'

export const Registro_exitoso = 'Registro_exitoso'
export const Registro_error = 'Registro_error'
export const Obtener_usuario = 'Obtener_usuario'
export const Login_exitoso = 'Login_exitoso'
export const Login_error = 'Login_error'
export const Cerrar_sesion = 'Cerrar_sesion'