export const Formulario_proyecto = 'Formulario_proyecto'
export const Obtener_proyecto = 'Obtener_proyecto'
export const Agregar_proyecto = 'Agregar_proyecto'
export const Actual_proyecto = 'Actual_proyecto'
export const Eliminar_proyecto = 'Eliminar_proyecto'

export const Tareas_proyecto = 'Tareas_proyecto'
export const Agregar_tarea = 'Agregar_tarea'
export const Eliminar_tarea = 'Eliminar_tarea'
export const Estado_tarea = 'Estado_tarea'
export const Seleccionar_tarea = 'Seleccionar_tarea'
export const Actualizar_tarea = 'Actualizar_tarea'